version: '3.3'

services:
  SonarQube:
    image: sonarqube:8.9-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sms
      SONAR_JDBC_USERNAME: sms
      SONAR_JDBC_PASSWORD: sms
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"
  db:
    build:
      context: .
      dockerfile: DockerFile
    container_name: sms_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sms
      POSTGRES_DB: sms
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
#    volumes:
#      - ./scripts:/docker-entrypoint-initdb.d postgres
volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  postgresql:
  postgresql_data:
